### ISSUE TITLE
Redesign verida auth client QR Modal 

### ISSUE THREAD

**Issue by cmcWebCode40** [verida/vault-auth-client#5] opened 2021-08-18 00:17 UTC
### Prototype Link
[Figma prototype link](https://www.figma.com/file/CetBoC3oZEHpRfILcewxFT/Vault-mobile-app?node-id=2505%3A22864)

**Comment by tahpot** [comment] 2021-08-19 11:48
FYI: This is a dupe of #3

**Closed** 2021-08-23 05:23 UTC
